2.product-introduction-1=Product Introduction
4.restrictions=Limits
3.deployment-guide=Deployment Guide
3.installation-planning=Installation planning
9.deploy-appendix=Appendix
4.user-guide-2=User Guide
3.features=Features
1.cluster-features-1=Clusters
2.tenant-functions-1=Tenants
3.host-features-1=Hosts
5.obproxy-1=OBProxy
6.monitoring-1=Monitoring
7.system-management-features-1=System management
8.user-center=Personal center
4.cluster-features=Manage clusters
2.basic-operations=Basic cluster operations
6.manage-a-zone=Manage zones of a cluster
7.manage-observer=Manage OBServers of a cluster
8.backup-and-recovery=Backup and recovery
6.cluster-resource-management=Cluster resource management
7.merge-management=Major compaction management
9.parameters-1=Manage parameters
5.tenant-functions=Manage tenants
2.manage-basic-tenant-operations=Basic tenant operations
9.sql-diagnostics=SQL diagnostics
10.merge-management=Tenant major compaction management
12.session-management=Manage sessions
13.parameters=Manage parameters
6.host-features=Manage hosts
7.manage-software-packages=Manage software packages
8.obproxy=Manage OBProxies
9.alert-management=Manage alerts
10.system-management-features=Use system management
11.management-user-center=User center management
13.appendix-2=Appendix
5.alarm-reference=Alert Reference
2.ob-alert=OceanBase alerts
3.application-alert=Application alerts
4.oas-alert=OAS alerts
5.appendix=Appendix
6.api-reference=API Reference
3.cluster-information=Cluster information
4.tenant-information=Tenant information
5.host-module=Hosts
6.software-package-1=Software packages
7.obproxy-management=OBProxy management
8.monitoring=Monitoring
9.alert=Alerts
1.alert-events=Alert events
2.alert-notification=Alert notifications
10.task-management=Task management
12.ob-user-and-permission-management=OceanBase user and privilege management
13.ocpagent-management=OCP Agent management
14.sql-performance=SQL performance
15.backup-and-restoration-3=Backup and recovery
16.other=Others
17.appendix-1=Appendix
1.oceanbase-cloud-platform-documentation=Document Overview