200.product-introduction=产品简介
400.restrictions=使用限制
300.deployment-guide=部署指南
300.installation-planning=安装规则
900.deploy-appendix=附录
500.quickstart=快速入门
600.cluster-functions=集群管理
200.create-a-cluster=新建集群
300.manage-a-cluster=管理集群
500.manage-a-zone=管理 Zone
600.manage-an-observer=管理 OBServer
1000.manage-cluster-resource=管理集群资源
1100.manage-cluster-merge=管理集群合并
1300.manage-cluster-parameters=管理集群参数
700.tenant-functions=租户管理
600.manage-a-tenant=管理租户
900.manage-tenant-topulogy=管理拓扑图
1000.manage-tenant-replica=管理副本
1200.manage-users-and-permissions-under-tenants=管理租户用户与权限
1250.manage-resource-isolation=管理租户资源隔离
1400.manage-tenant-merge=管理租户合并
1600.manage-tenant-parameters=管理租户参数
800.obproxy-functions=OBProxy 管理
300.manage-a-obproxy-cluster=管理 OBProxy 集群
400.manage-a-obproxy-server=管理 OBProxy Server
850.host-features=主机管理
900.monitoring-and-alerts-functions=监控告警
100.performance-monitoring-overview=使用监控管理
200.alert-management=使用告警管理
300.manage-alert-rules=管理告警规则
400.manage-alert-templates=管理告警模板
500.manage-alert-channels=管理告警通道
600.manage-alert-push=管理告警推送
800.manage-blocking-conditions=管理告警屏蔽
1000.diagnosis-and-tuning-fuctions=诊断调优
100.manage-sql-diagnosis=SQL 诊断
100.sql-diagnostics-introduction=SQL 诊断介绍
300.manage-session=会话管理
1100.backup-and-restoration-functions=备份恢复
400.backup-now=立即备份
500.regular-backup=定时备份
100.manage-cluster-backup-strategy=管理集群备份策略
200.manage-tenant-backup-strategy=管理租户备份策略
600.manage-backup-tasks=管理备份任务
800.regular-recovery=定时恢复
1000.manage-backup-and-recovery-service=管理备份恢复服务
1200.manage-disaster-recovery=容灾管理
1300.log-service=日志服务
1500.manage-software-packages=软件包管理
1600.system-management-features=系统管理
300.manage-system-parameter=管理系统参数
400.manage-roles=管理角色
500.manage-users=用户管理
600.management-user-center=管理个人中心
300.manage-password-box=管理密码箱
1800.sql-tuning-practices=SQL 调优实践
100.how-to-locate-abnormal-sql=常见的异常 SQL 定位
200.custom-exception-sql-rules=自定义异常 SQL 规则
300.common-sql-performance-tuning=常见 SQL 性能调优场景
100.execution-plan-optimization=执行计划优化
200.index-optimization=索引优化
1900.reference-guide=参考指南
100.alarm-reference=告警参考
200.ob-alert=OceanBase 告警
300.application-alert=应用告警
400.oas-alert=OAS 告警
500.appendix=附录
200.api-reference=API 参考
450.cluster-information=集群信息
500.tenant-information=租户信息
1900.ob-database-management=OceanBase 数据库管理
600.host-module=主机模块
700.software-package=软件包接口
800.obproxy-management=OBProxy 管理
900.monitoring=监控
1000.alert=告警
200.alert-events=告警事件
300.alert-notification=告警通知
1100.task-management=任务管理接口
1300.ob-user-and-permission-management=OceanBase 用户与权限管理
1400.ocpagent-management=OCP Agent 管理
1500.sql-performance=SQL 性能
1600.backup-and-restoration-3=备份恢复
2100.appendix=附录