2.product-introduction-1=产品简介
4.restrictions=使用限制
3.deployment-guide=部署指南
3.installation-planning=安装规则
9.deploy-appendix=附录
4.user-guide-2=用户指南
3.features=功能介绍
1.cluster-features-1=集群功能
2.tenant-functions-1=租户功能
3.host-features-1=主机功能
5.obproxy-1=OBProxy 功能
6.monitoring-1=告警管理功能
7.system-management-features-1=系统管理功能
8.user-center=个人中心
4.cluster-features=管理集群
2.basic-operations=集群基础操作
6.manage-a-zone=管理集群 Zone
7.manage-observer=管理集群 OBServer
6.cluster-resource-management=集群资源管理
7.merge-management=集群合并管理
8.backup-and-recovery=集群备份恢复
9.parameters-1=参数管理
5.tenant-functions=管理租户
2.manage-basic-tenant-operations=租户基础操作
9.sql-diagnostics=SQL 诊断
10.merge-management=租户合并管理
12.session-management=会话管理
13.parameters=参数管理
6.host-features=管理主机
7.manage-software-packages=管理软件包
8.obproxy=管理 OBProxy
9.alert-management=使用告警管理
10.system-management-features=使用系统管理
11.management-user-center=管理个人中心
13.appendix-2=附录
5.alarm-reference=告警参考
2.ob-alert=OB 告警
3.application-alert=应用告警
4.oas-alert=OAS 告警
5.appendix=附录
6.api-reference=API 参考
3.cluster-information=集群信息
4.tenant-information=租户信息
5.host-module=主机模块
6.software-package-1=软件包接口
7.obproxy-management=OBProxy 管理
8.monitoring=监控
9.alert=告警
1.alert-events=告警事件
2.alert-notification=告警通知
10.task-management=任务管理接口
12.ob-user-and-permission-management=OB 用户与权限管理
13.ocpagent-management=OCP Agent 管理
14.sql-performance=SQL 性能
15.backup-and-restoration-3=备份恢复
16.other=其它
17.appendix-1=附录
1.oceanbase-cloud-platform-documentation=OceanBase 云平台文档