200.product-introduction=Product Introduction
400.restrictions=Limits
300.deployment-guide=Deployment Guide
300.installation-planning=Installation planning
900.deploy-appendix=Appendix
500.quickstart=Quick Start
600.cluster-functions=Clusters Management
200.create-a-cluster=Create a cluster
300.manage-a-cluster=Manage clusters
500.manage-a-zone=Manage zones of a cluster
600.manage-an-observer=Manage OBServers of a cluster
1000.manage-cluster-resource=Manage cluster resource
1100.manage-cluster-merge=Manage major compaction of a cluster
1300.manage-cluster-parameters=Manage cluster parameters
700.tenant-functions=Tenants Management
600.manage-a-tenant=Manage tenants
900.manage-tenant-topulogy=Manage topulogy of a tenant
1000.manage-tenant-replica=Manage replicas of a tenant
1200.manage-users-and-permissions-under-tenants=Manage users and permissions under a tenant
1250.manage-resource-isolation=Manage resource isolation
1400.manage-tenant-merge=Manage major compaction under a tenant
1600.manage-tenant-parameters=Manage tenant parameters
800.obproxy-functions=OBProxies management
300.manage-a-obproxy-cluster=Manage OBProxy Clusters
400.manage-a-obproxy-server=Manage OBProxy Servers
850.host-features=Hosts management
900.monitoring-and-alerts-functions=Monitoring and Alerts management
100.performance-monitoring-overview=Manage monitoring
200.alert-management=Use the alert feature
300.manage-alert-rules=Manage alert rules
400.manage-alert-templates=Manage alert templates
500.manage-alert-channels=Manage alert channels
600.manage-alert-push=Manage alert push
800.manage-blocking-conditions=Manage blocking conditions
300.use-the-inspection-feature=Use the inspection feature
200.configure-the-rules=Configure Scheduling Rules
1000.diagnosis-and-tuning-fuctions=Diagnosis and tuning fuctions
100.manage-sql-diagnosis=SQL Diagnostics
100.sql-diagnostics-introduction=SQL Diagnostics Introduction
300.manage-session=Manage sessions
1100.backup-and-restoration-functions=Use backup and recovery
400.backup-now=Backup now
500.regular-backup=Regular backup
100.manage-cluster-backup-strategy=Manage cluster-level backup strategy
200.manage-tenant-backup-strategy=Manage tenant-level backup strategy
600.manage-backup-tasks=Manage backup tasks
800.regular-recovery=Regular recovery
1000.manage-backup-and-recovery-service=Manage backup and recovery service
1200.manage-disaster-recovery=Disaster recovery management
1300.log-service=Log service
1500.manage-software-packages=Software packages management
1600.system-management-features=System management
300.manage-system-parameter=Manage system parameters
400.manage-roles=Manage roles
500.manage-users=Manage users
600.management-user-center=User center management
300.manage-password-box=Manage password box
1800.sql-tuning-practices=SQL Tuning Practices
100.how-to-locate-abnormal-sql=Locate General Abnormal SQL Statements
200.custom-exception-sql-rules=Customize Abnormal SQL Statement Determining Rules
300.common-sql-performance-tuning=General SQL Performance Tuning Scenarios
100.execution-plan-optimization=Execution Plan Optimization
200.index-optimization=Index Optimization
1900.reference-guide=Reference guide
100.alarm-reference=Alarm reference
200.ob-alert=OceanBase alerts
300.application-alert=Application alerts
400.oas-alert=OAS alerts
500.appendix=Appendix
200.api-reference=API Reference
450.cluster-information=Cluster information
500.tenant-information=Tenant information
1900.ob-database-management=OceanBase database management
600.host-module=Hosts
700.software-package=Software packages
800.obproxy-management=OBProxy management
900.monitoring=Monitoring
1000.alert=Alerts
200.alert-events=Alert events
300.alert-notification=Alert notifications
1100.task-management=Task management
1300.ob-user-and-permission-management=OceanBase user and privilege management
1400.ocpagent-management=OCP Agent management
1500.sql-performance=SQL performance
1600.backup-and-restoration-3=Backup and recovery
2100.appendix=Appendix