200.product-introduction-1=Product Introduction
400.restrictions=Limits
300.deployment-guide=Deployment Guide
300.installation-planning=Installation planning
900.deploy-appendix=Appendix
400.user-guide-2=User Guide
300.features=Features
100.cluster-features-1=Clusters
200.tenant-functions-1=Tenants
300.host-features-1=Hosts
500.obproxy-1=OBProxy
700.monitoring-1=Monitoring
900.system-management-features-1=System management
1000.user-center=Personal center
400.cluster-features=Manage clusters
200.basic-operations=Basic cluster operations
600.manage-a-zone=Manage zones of a cluster
700.manage-observer=Manage OBServers of a cluster
700.cluster-resource-management=Cluster resource management
900.merge-management=Major compaction management
1000.cluster-backup-and-recovery=Backup and recovery
1100.parameters-1=Manage parameters
500.tenant-functions=Manage tenants
200.manage-basic-tenant-operations=Basic tenant operations
1000.sql-diagnostics=SQL diagnostics
1100.merge-management=Tenant major compaction management
1200.backup-and-recover-a-tenant=Backup and recovery
1300.session-management=Manage sessions
1400.parameters=Manage parameters
600.host-features=Manage hosts
700.manage-software-packages=Manage software packages
800.obproxy=Manage OBProxies
900.alert-management=Manage alerts
1000.system-management-features=Use system management
1100.management-user-center=User center management
1300.appendix-2=Appendix
500.alarm-reference=Alert Reference
200.ob-alert=OceanBase alerts
300.application-alert=Application alerts
400.oas-alert=OAS alerts
500.appendix=Appendix
600.api-reference=API Reference
300.cluster-information=Cluster information
400.tenant-information=Tenant information
1900.ob-database-management=Database management
500.host-module=Hosts
600.software-package-1=Software packages
700.obproxy-management=OBProxy management
800.monitoring=Monitoring
900.alert=Alerts
100.alert-events=Alert events
200.alert-notification=Alert notifications
1000.task-management=Task management
1200.ob-user-and-permission-management=OceanBase user and privilege management
1300.ocpagent-management=OCP Agent management
1400.sql-performance=SQL performance
1500.backup-and-restoration-3=Backup and recovery
1600.other=Others
1700.appendix-1=Appendix
100.oceanbase-cloud-platform-documentation=Document Overview
