200.product-introduction-1=产品简介
400.restrictions=使用限制
300.deployment-guide=部署指南
300.installation-planning=安装规则
900.deploy-appendix=附录
400.user-guide-2=用户指南
300.features=功能介绍
100.cluster-features-1=集群功能
200.tenant-functions-1=租户功能
300.host-features-1=主机功能
500.obproxy-1=OBProxy 功能
700.monitoring-1=监控功能
900.system-management-features-1=系统管理功能
1000.user-center=个人中心
400.cluster-features=管理集群
200.basic-operations=集群基础操作
600.manage-a-zone=管理集群 Zone
700.manage-observer=管理集群 OBServer
700.cluster-resource-management=集群资源管理
900.merge-management=集群合并管理
1000.cluster-backup-and-recovery=集群备份恢复
1100.parameters-1=参数管理
500.tenant-functions=管理租户
200.manage-basic-tenant-operations=租户基础操作
1000.sql-diagnostics=SQL 诊断
1100.merge-management=租户合并管理
1200.backup-and-recover-a-tenant=租户备份恢复
1300.session-management=会话管理
1400.parameters=参数管理
600.host-features=管理主机
700.manage-software-packages=管理软件包
800.obproxy=管理 OBProxy
900.alert-management=使用告警管理
1000.system-management-features=使用系统管理
1100.management-user-center=管理个人中心
1300.appendix-2=附录
500.alarm-reference=告警参考
200.ob-alert=OB 告警
300.application-alert=应用告警
400.oas-alert=OAS 告警
500.appendix=附录
600.api-reference=API 参考
300.cluster-information=集群信息
400.tenant-information=租户信息
1900.ob-database-management=数据库管理
500.host-module=主机模块
600.software-package-1=软件包接口
700.obproxy-management=OBProxy 管理
800.monitoring=监控
900.alert=告警
100.alert-events=告警事件
200.alert-notification=告警通知
1000.task-management=任务管理接口
1200.ob-user-and-permission-management=OB 用户与权限管理
1300.ocpagent-management=OCP Agent 管理
1400.sql-performance=SQL 性能
1500.backup-and-restoration-3=备份恢复
1600.other=其它
1700.appendix-1=附录
100.oceanbase-cloud-platform-documentation=OceanBase 云平台文档
