200.product-introduction=产品简介
400.restrictions=使用限制
300.deployment-guide=部署 OceanBase 云平台
100.deploying-enterprise-ocp=部署企业版 OceanBase 云平台
100.deployment-overview=概述
200.prepare-the-deployment-environment=准备部署环境
300.deployment=部署 OCP
100.planning-resources=规划资源
100.planning-resources-of-single-node=规划单节点 OCP 资源
200.planning-resources-of-high-availability=规划高可用 OCP 资源
200.deploying-ocp=部署 OCP
100.deploying-a-single-point-of-ocp=部署单节点 OCP
200.deploying-a-high-availability-of-ocp=部署高可用 OCP
400.deployment-faq=部署常见问题
200.f5-ltm-and-alert-configuration=F5 LTM 及告警配置
200.deploying-community-ocp=部署社区版 OceanBase 云平台
300.installation-planning=安装规划
700.deploy-appendix=附录
400.upgrade-guide=升级 OceanBase 云平台
100.upgrade-enterprise-ocp=升级企业版 OceanBase 云平台
400.upgrade-ocp-guide=升级 OCP
500.verify-after-upgrade=升级后验证
600.upgrade-appendix=附录
200.upgrade-community-ocp=升级社区版 OceanBase 云平台
500.quickstart=快速入门
600.cluster-functions=集群管理
200.create-a-cluster=新建集群
300.manage-a-cluster=管理集群
400.manage-arbitration-services=管理仲裁服务
500.manage-a-zone=管理 Zone
600.manage-an-observer=管理 OBServer
1000.manage-cluster-resource=管理集群资源
1100.manage-cluster-merge=管理集群合并
1300.manage-cluster-parameters=管理集群参数
700.tenant-functions=租户管理
600.manage-a-tenant=管理租户
900.manage-tenant-topulogy=管理拓扑图
1000.manage-tenant-replica=管理副本
1200.manage-users-and-permissions-under-tenants=管理租户用户与权限
200.user-management-under-an-oracle-tenant=管理 Oracle 租户用户
1250.manage-resource-isolation=管理租户资源隔离
1400.manage-tenant-merge=管理租户合并
1600.manage-tenant-parameters=管理租户参数
800.obproxy-functions=OBProxy 管理
300.manage-a-obproxy-cluster=管理 OBProxy 集群
400.manage-a-obproxy-server=管理 OBProxy Server
820.binlog-service-fuctions=Binlog 服务管理
300.manage-a-binlog-cluster=管理 Binlog 集群
500.manage-binlog-instance=管理 Binlog 实例
600.manage-binlog-server=管理 Binlog Server
850.host-features=主机管理
860.alert-management=告警中心
300.manage-alert-rules=管理告警规则
400.manage-alert-templates=管理告警模板
500.manage-alert-channels=管理告警通道
600.manage-alert-push=管理告警推送
800.manage-blocking-conditions=管理告警屏蔽
870.manage-monitor-dashboard=监控大盘
880.manage-performance-monitoring=性能监控
100.performance-monitoring-overview=使用监控管理
200.manage-custom-monitoring=使用自定义监控功能
300.manage-indicator-items=管理指标项
400.manage-chart=管理图表
1000.diagnosis-and-tuning-fuctions=诊断调优
1050.operation-and-maintenance-functions=运维管理
100.manage-information-collection=管理信息采集
200.manage-plans=管理预案
300.use-the-inspection-feature=巡检服务
200.configure-the-rules=配置调度规则
400.initate-a-inspection=发起巡检
600.manage-inspection-report=管理巡检报告
100.manage-sql-diagnosis=SQL 诊断
100.sql-diagnostics-introduction=SQL 诊断介绍
200.manage-transaction-diagnostics=事务诊断
300.manage-session=会话管理
600.manage-the-reports=诊断报告
1100.backup-and-restoration-functions=备份恢复
400.backup-now=立即备份
500.regular-backup=定时备份
100.manage-cluster-backup-strategy=管理集群备份策略
200.manage-tenant-backup-strategy=管理租户备份策略
600.manage-backup-tasks=管理备份任务
800.regular-recovery=定时恢复
1000.manage-backup-and-recovery-service=管理备份恢复服务
1200.manage-disaster-recovery=容灾管理
100.switching-primary-and-standby-tenants=主备租户切换
200.switching-primary-and-standby-databases=主备库切换
300.ocp-multi-cluster-mode=管理多集群模式 OCP
400.ocp-multi-zone-mode=管理多 AZ 模式 OCP
1300.log-service=日志服务
1500.manage-software-packages=软件包管理
1600.system-management-features=系统管理
100.manage-password-box=管理凭据
200.manage-users=管理用户
100.manage-a-user=管理用户
200.manage-a-role=管理角色
300.manage-tags=管理标签
450.manage-external-integration=管理外部集成
500.manage-system-parameter=管理系统参数
700.manage-user-center=管理个人中心
1800.sql-tuning-practices=SQL 调优实践
100.how-to-locate-abnormal-sql=常见的异常 SQL 定位
200.custom-exception-sql-rules=自定义异常 SQL 规则
300.common-sql-performance-tuning=常见 SQL 性能调优场景
100.execution-plan-optimization=执行计划优化
200.index-optimization=索引优化
1850.ocp-om-best-practices=运维最佳实践
1900.reference-guide=参考指南
100.alarm-reference=告警参考
200.ob-alert=OceanBase 告警
300.application-alert=应用告警
400.oas-alert=OAS 告警
500.appendix=附录
200.api-reference=API 参考
500.cluster-management=集群管理
600.tenant-management=租户管理
700.obproxy-management=OBProxy 管理
800.database-management=数据库管理
900.monitoring=监控
1000.alert=告警
200.alert-events=告警事件
300.alert-notification=告警通知
1100.inspection=巡检
1200.sql-performance=SQL 性能
1300.backup-and-restoration=备份恢复
1400.host-management=主机管理
1500.software-package=软件包管理
1600.om-task-management=运维任务管理
1700.system-management=系统管理
100.health-examination=健康检查
200.ocp-historical-events=操作审计
300.ocpagent-management=Agent 管理
300.monitoring-indicator-reference=监控指标参考
300.ob-cluster=OceanBase 集群
400.oceanbase-database-tenant=OceanBase 租户
450.binlog-service=Binlog 服务
500.obproxy-cluster=OBProxy 集群
600.host=主机
2000.faq=常见问题
300.common-o-m-problems=运维常见问题
400.common-monitoring-problems=监控常见问题
2100.appendix=附录
2200.release-notes=版本发布记录
98.rn-43x=V4.3
99.rn-42x=V4.2
100.rn-41x=V4.1
200.rn-40x=V4.0
300.rn-33x=V3.3
400.rn-32x=V3.2
500.rn-31x=V3.1